[package]
name = "rustyjack-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
tokio = { version = "1.0", features = ["io-util", "net", "time", "sync"] }

rustyjack-ipc = { path = "../rustyjack-ipc" }
